# environment
env: dmcontrol
modality: 'state'
domain: cheetah
task: cheetah-run
tasks: [cheetah-run,cheetah-jump,cheetah-run-backwards]
action_repeat: 4
episode_length: 1000/${action_repeat}
train_steps: 2000000/${action_repeat}

# learning
batch_size: 512
max_buffer_size: 1000000
horizon: 25
horizons: [25, 15, 25]
update_freq: 2
vae_data_update_freq: 10
kl_coef: 0.02
num_episodes: 20

# architecture
enc_dim: 256
use_crelu: false

# misc
eval_freq: 20000
eval_episodes: 20
save_video: true
first_step_qr_only: true